### ISSUE TITLE
Just wondering...

### ISSUE THREAD

**Issue by dphoebus** [lethek/Serilog.Sinks.LINQPad#1]
Super helpful Serilog Sink... but couldn't find it on NuGet.  Are you still maintaining it or care if someone else does?  Thanks!

**Comment by lethek** [comment]
Hi Daniel,
I never actually released it to the public NuGet gallery, but rather only to a private feed. I'm happy to put it up there though and will do so today or tomorrow.
Michael

**Comment by dphoebus** [comment]
That is great.  Thank you!

**Comment by lethek** [comment]
You may have found it by now, but for the record: https://www.nuget.org/packages/Serilog.Sinks.LINQPad/

**Comment by dphoebus** [comment]
That is perfect.  Thank you for the work!
