### ISSUE TITLE
parameter values not escaped

### ISSUE THREAD

**Issue by mdonoughe** [lethek/Serilog.Sinks.LINQPad#2]
I'm trying to prototype something involving entity framework and XML, both of which lead to log messages containing angle brackets. This results in errors such as

    Cannot parse custom HTML: '...' - ''\' is an unexpected token. The expected token is '"' or ''', line 1, position 1016.

It seems like the parameter values are being written directly into the HTML string without any escaping.

**Comment by lethek** [comment]
Ooops! That was a pretty silly oversight on my part. Thanks for reporting it - I've committed a fix for it now. Will upload a new nuget package shortly too
