### ISSUE TITLE
Space in the `outputTemplate` is not rendered correctly

### ISSUE THREAD

**Issue by adamchester** [lethek/Serilog.Sinks.LINQPad#3]
When using the `outputTemplate` of `"[{Timestamp:HH:mm:ss} {Level:u3}] {Message}{NewLine}{Exception}"`, I noticed that the space between the `Timestamp` and the `Level` tokens is not rendered in the LINQPad results pane.

![image](https://cloud.githubusercontent.com/assets/570470/25689003/208d6d86-30c7-11e7-9cec-368589ca8909.png)

**Comment by lethek** [comment]
Thanks Adam, I think this should be fixed now in the commit I just pushed.
