### ISSUE TITLE
Consider if the `serilog-sinks-literate` style would work better?

### ISSUE THREAD

**Issue by adamchester** [lethek/Serilog.Sinks.LINQPad#4]
Have you seen the [`serilog-sinks-literate` project](https://github.com/serilog/serilog-sinks-literate)? Do you have any thoughts if this kind of colouring might be nicer to read within Linqpad than [`serilog-sinks-coloredconsole`](https://github.com/serilog/serilog-sinks-coloredconsole)?

**Comment by lethek** [comment]
Yep, I've been using the serilog-sinks-literate in some other (work) projects and I do actually much prefer its colouring scheme than the coloredconsole one.

Unfortunately when I hacked together this particular sink, the literate one did not yet exist, and I've still not gotten around to spending the time to redo it, basing it on serilog-sinks-literate. I would definitely like to do so.

**Comment by lethek** [comment]
I've released a new version completely re-done, based on [serilog-sinks-literate](https://github.com/serilog/serilog-sinks-literate). I had to tweak the colouring scheme so it displayed okay on LINQPad's default white background, but also made it user-configurable, see: [README.md](https://github.com/lethek/Serilog.Sinks.LINQPad/blob/master/README.md#custom-color-schemes)

Let me know what you think or if you have any problems with it?

The nuget package is published, but apparently not indexed yet: https://www.nuget.org/packages/Serilog.Sinks.LINQPad/2.0.1

**Comment by adamchester** [comment]
Looks really good! 👏 🎉
