### ISSUE TITLE
Version 2.0 (.NET 4.x) doesn't work in LinqPad 6.0 which supports .NET Core

### ISSUE THREAD

**Issue by scipbe** [lethek/Serilog.Sinks.LINQPad#5]

**Comment by lethek** [comment]
Thanks for the heads-up. I've just started reworking the sink this evening, basing it on the Serilog.Sinks.Console project (rather than the deprecated LiterateConsoleSink). I'll multi-target .NET 4.5 and .NET Core 3.0. Hopefully I should have it all done in the next couple days.

**Comment by lethek** [comment]
Just released version 3.0 - let me know if you have any issues with it.

If you customise the themes at all, that's a breaking-change, see the updated documentation which describes how that works.

**Comment by scipbe** [comment]
Thanks Michael, it works perfect!
